#pragma once

#include "GameConfig.h"

char map_one[ROWS][COLUMNS] = {
	"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
	"X           XXXXX         X",
	"X XXX XXXXX XXXXX XXXXX X X",
	"X XXX XXXXX XXXXX XXXXX X X",
	"X                         X",
	"X XXX XX XXXXXXXXXXX XX XXX",
	"X     XX     XXX     XX   X",
	"X XXX XXXXXX XXX XXXXXX X X",
	"X XXX XX             XX X X",
	"      XX XXXXXXXXXXX XX    ",
	"X XXX XX XXXXXXXXXXX XX X X",
	"X XXX XX             XX X X",
	"X XXX XXXXXX XXX XXXXXX X X",
	"X     XX     XXX     XX   X",
	"X XXX XX XXXXXXXXXXX XX XXX",
	"X XXX                   XXX",
	"X XXX XXXX XXXXXXXX XXX XXX",
	"X XXX XXXX          XXX XXX",
	"X          XXXXXXXX       X",
	"X XXX XXXXXXXXXXXXXX XX X X",
	"X XXX XX XXXXXXXXXXX XX X X",
	"X XXX XX             XX X X",
	"X XXX XXXXXX XXX XXXXXX X X",
	"      XX     XXX     XX    ",
	"X XXX XX XXXXXXXXXXX XX X X",
	"X XXX                   X X",
	"X XXX XXXX XXXXXXXX XXX X X",
	"X XXX XXXX          XXX X X",
	"X          XXXXXXXX       X",
	"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
};